# Task-1

In [1]:
array = ['w','r','b']

list1=[]
for i in array:
    for j in array:
        for k in array:
            if i not in list1:
                list1.append(i+j+k)
            
len(list1)

27

In [2]:
r=4
w=6
b=6

p_r = 4/15
p_w = 6/15
p_b = 5/15

In [3]:
def fact(x):
    fact1=1
    for i in range(1,x+1):
        fact1*=i
    return fact1

def combination(n,r):
    return fact(n)/(fact(r)*fact(n-r))

total_prob=[]
for i in list1:
    r1=0
    r2=0
    r3=0
    for j in i:
        if j=='w':
            r1+=1
        if j=='r':
            r2+=1
        if j=='b':
            r3+=1
        
    temp1=combination(6,r1)
    temp2=combination(4,r2)
    temp3=combination(5,r3)
    temp4=combination(15,3)
    
    total_prob.append(temp1*temp2*temp3/temp4)
            

max_value = max(total_prob)
max_index = total_prob.index(max_value)
print("Combination: " , list1[max_index])       
print("Probability: " , total_prob[max_index])            

Combination:  wrb
Probability:  0.26373626373626374


# Task-2&3

In [17]:
import pandas as pd
import numpy as np
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score

In [5]:
df = pd.read_csv("Iris.csv")
df = df.drop('Id' , axis=1)
df

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0              5.1           3.5            1.4           0.2     Iris-setosa
1              4.9           3.0            1.4           0.2     Iris-setosa
2              4.7           3.2            1.3           0.2     Iris-setosa
3              4.6           3.1            1.5           0.2     Iris-setosa
4              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
145            6.7           3.0            5.2           2.3  Iris-virginica
146            6.3           2.5            5.0           1.9  Iris-virginica
147            6.5           3.0            5.2           2.0  Iris-virginica
148            6.2           3.4            5.4           2.3  Iris-virginica
149            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [6]:
data=[]
for i in df['Species'].unique():
    data.append(df[df['Species']==i])
for i in data:
    i.drop('Species',axis=1,inplace=True)


C:\Users\anshu\anaconda3\lib\site-packages\pandas\core\frame.py:4906: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(


In [7]:
data = np.array(data)
mean_vector = np.mean(data , axis=1)
mean_vector

array([[5.006, 3.418, 1.464, 0.244],
       [5.936, 2.77 , 4.26 , 1.326],
       [6.588, 2.974, 5.552, 2.026]])

In [8]:
co_var=[]
for i in df['Species'].unique():
    co_var.append(df[df['Species']==i].cov())
    
co_var

[               SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
 SepalLengthCm       0.124249      0.100298       0.016139      0.010547
 SepalWidthCm        0.100298      0.145180       0.011682      0.011437
 PetalLengthCm       0.016139      0.011682       0.030106      0.005698
 PetalWidthCm        0.010547      0.011437       0.005698      0.011494,
                SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
 SepalLengthCm       0.266433      0.085184       0.182898      0.055780
 SepalWidthCm        0.085184      0.098469       0.082653      0.041204
 PetalLengthCm       0.182898      0.082653       0.220816      0.073102
 PetalWidthCm        0.055780      0.041204       0.073102      0.039106,
                SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
 SepalLengthCm       0.404343      0.093763       0.303290      0.049094
 SepalWidthCm        0.093763      0.104004       0.071380      0.047629
 PetalLengthCm       0.303290      0.071380      

In [9]:
co_vari = np.array(co_var)

for k in range(3):
    for i in range(4):
        for j in range(4):
            if i!=j:
                co_vari[k][i][j]=0
                
                
co_vari
                

array([[[0.12424898, 0.        , 0.        , 0.        ],
        [0.        , 0.14517959, 0.        , 0.        ],
        [0.        , 0.        , 0.03010612, 0.        ],
        [0.        , 0.        , 0.        , 0.01149388]],

       [[0.26643265, 0.        , 0.        , 0.        ],
        [0.        , 0.09846939, 0.        , 0.        ],
        [0.        , 0.        , 0.22081633, 0.        ],
        [0.        , 0.        , 0.        , 0.03910612]],

       [[0.40434286, 0.        , 0.        , 0.        ],
        [0.        , 0.10400408, 0.        , 0.        ],
        [0.        , 0.        , 0.30458776, 0.        ],
        [0.        , 0.        , 0.        , 0.07543265]]])

In [10]:
det = np.linalg.det(co_vari)
det

array([6.24194290e-06, 2.26550291e-04, 9.66211009e-04])

In [11]:
inverse_co_var = np.linalg.inv(co_vari)
inverse_co_var

array([[[ 8.04835584,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  6.88802047,  0.        ,  0.        ],
        [ 0.        ,  0.        , 33.21583514,  0.        ],
        [ 0.        ,  0.        ,  0.        , 87.00284091]],

       [[ 3.75329371,  0.        ,  0.        ,  0.        ],
        [ 0.        , 10.15544041,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  4.52865065,  0.        ],
        [ 0.        ,  0.        ,  0.        , 25.57144348]],

       [[ 2.47314867,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  9.61500726,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  3.28312607,  0.        ],
        [ 0.        ,  0.        ,  0.        , 13.2568584 ]]])

In [12]:
input_list=[6.7,3.0,5.2,2.3]
input1 = np.array(input_list)

In [13]:
def calcu(det1 , x , mean1 , inverse_co_var1):
    
    temp1 = 1/((2*3.14)**4)*det1
    temp1 = temp1**(1/2)
    
    temp2 = (x - mean1).T
    temp2 = (-0.5) * temp2
    
    
    temp3 = np.dot((inverse_co_var1),(x-mean1))
    temp3.reshape(4,1)
    
    temp4 = np.dot(temp2.T , temp3)
    temp5 = 2.718**temp4
        
    return temp1 * temp5


In [14]:

prob1 = calcu(det[0] , input1 , mean_vector[0] , inverse_co_var[0])
prob1 *= 1/3
prob2 = calcu(det[1] , input1 , mean_vector[1] , inverse_co_var[1])
prob2*=1/3
prob3 = calcu(det[2] , input1 , mean_vector[2] , inverse_co_var[2])
prob3*=1/3

3.4153826884887703e-191

In [ ]:
if prob1>prob2 and prob1>prob3:
    check_list.append(0)
    
if prob2>prob1 and prob2>prob3:
    check_list.append(1)
    
if prob3>prob1 and prob3>prob2:
    check_list.append(2)

# Build-in Gaussian Function

In [23]:
df = pd.read_csv("Iris.csv")
df = df.drop('Id' , axis=1)

In [24]:
labels = df['Species']
le = LabelEncoder()

X = df.drop("Species", axis = 1)
y = le.fit_transform(labels)

In [25]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 52)

In [33]:
clf1 = GaussianNB()
clf1.fit(X_train, y_train)
predict = clf1.predict(X_test)
re = clf1.score(X_test,y_test)
re

0.9111111111111111

In [ ]:
xx_test = np.array(X_test)
xx_test[0]

In [45]:
check_list=[]
n = 149*(0.3)
for i in range(0,int(n)+1):
    prob1 = calcu(det[0] , xx_test[i] , mean_vector[0] , inverse_co_var[0])
    prob1 *= 1/3
    prob2 = calcu(det[1] , xx_test[i] , mean_vector[1] , inverse_co_var[1])
    prob2*=1/3
    prob3 = calcu(det[2] , xx_test[i] , mean_vector[2] , inverse_co_var[2])
    prob3*=1/3
    
    if prob1>prob2 and prob1>prob3:
        check_list.append(0)
    
    if prob2>prob1 and prob2>prob3:
        check_list.append(1)

    if prob3>prob1 and prob3>prob2:
        check_list.append(2)
    

In [52]:
count=0
for i in range(0,45):
    if check_list[i]==y_test[i]:
        count+=1
    

In [53]:
accu = count/len(y_test)
accu

0.8888888888888888

In [54]:
print("Accuracy of build in function: " , re*100)
print("Accuracy of My MOdel: " , accu*100)

Accuracy of build in function:  91.11111111111111
Accuracy of My MOdel:  88.88888888888889


In [55]:
# The accuracy of build in function is greater than my model. 
# Hence, we can conclude that build in function is better than my created model.


# Task-4

In [56]:
pi = 3.143
r1 = 8

# 8 inch pizza
area1 = pi*(r1**2)
area1

201.152

In [58]:
# 2 five inch pizz
r2 = 5
area2 = pi*(r2**2)
area2 *= 2
area2

157.14999999999998

In [59]:
#As we can clearly see the results and conclude that 8 inch pizz has greater area than 2 five inch pizza..
