# Ans Hussain
# 20i-1824
# AI(K)
# Lab-12

In [1]:
import pandas as pd
import numpy as np


# Gradient Descent From Scratch

In [2]:
def hypothesis(X1,thetas1):
    return np.dot(X1,thetas1)

In [3]:
def loss_fun(y_act,y_pred):
    return np.mean((y_act-y_pred)**2)

In [4]:
def gradient_descent(alpha,thetas2,g_thetas):
    return (thetas2-alpha*g_thetas)

In [5]:
def der_loss_fun(x,y,thetas3):
    hp=hypothesis(x,thetas3)
    diff = (y-hp).T
    f1=np.dot(diff,X)
    f1=-2*f1/float(x.shape[0])
    return f1

# Task-1
# Reading Csv File

In [6]:
df = pd.read_csv ("Advertising.csv")
df = df.iloc[: , 1:]
df

TV  radio  newspaper  sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3    9.3
3    151.5   41.3       58.5   18.5
4    180.8   10.8       58.4   12.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1    9.7
197  177.0    9.3        6.4   12.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   13.4

[200 rows x 4 columns]



# Preparing for applying functions

In [7]:
one = np.ones(200)
X = df.iloc[: , :-1]
X['One'] = one
X = np.array(X)
Y = df.iloc[:,-1:]
Y = np.array(Y)
thetas = np.array([[100] , [50] , [75] , [1]])
print("X Shape: " , X.shape)
print("Y Shape: " , Y.shape)
print("Thetas Shape: " , thetas.shape)
alpha = 0.0001

X Shape:  (200, 4)
Y Shape:  (200, 1)
Thetas Shape:  (4, 1)


# Applying Functions

In [8]:
y_pred = hypothesis(X , thetas)
y_pred.shape

(200, 1)

In [9]:
MSE = loss_fun(Y , y_pred)
MSE

408872809.05125

In [10]:
g_thetas = der_loss_fun(X , Y , thetas)
g_thetas = g_thetas.T
g_thetas.shape

(4, 1)

In [11]:
n_thetas = gradient_descent (alpha , thetas , g_thetas)
n_thetas

array([[-582.53413416],
       [ -39.71310866],
       [ -46.20737077],
       [  -2.6291955 ]])

# Gradient Descent 100 Times

In [12]:
for i in range(100):
    y_pred = hypothesis(X , n_thetas)
    g_thetas = der_loss_fun(X , Y , n_thetas)
    g_thetas = g_thetas.T
    n_thetas = gradient_descent (alpha , n_thetas , g_thetas)
    print(loss_fun(Y , y_pred))

10245565150.43966
258935092657.69727
6545610952253.798
165467377974489.84
4182872848598497.5
1.0573942473738133e+17
2.6730016307310413e+18
6.757118015031614e+19
1.7081412650160958e+21
4.318034071271358e+22
1.0915618410801986e+24
2.759374366287891e+25
6.975460855055007e+26
1.7633364553524404e+28
4.457562760920101e+29
1.126833492679661e+31
2.8485380651433575e+32
7.200859010034219e+33
1.820315168573372e+35
4.601600042885104e+36
1.1632448776041003e+38
2.940582911729522e+39
7.433540458450756e+40
1.879135035676455e+42
4.750291603367001e+43
1.2008328240708863e+45
3.035602004609513e+46
7.673740545457749e+47
1.93985554989041e+49
4.9037878361264775e+50
1.2396353503280435e+52
3.133691450641499e+53
7.921702220919208e+54
2.002538126849408e+56
5.062243994599702e+57
1.2796917031077256e+59
3.234950462185783e+60
8.177676285141208e+61
2.0672461667117898e+63
5.225820348929103e+64
1.3210423973222382e+66
3.339481457452914e+67
8.441921642543259e+68
2.1340451182860077e+70
5.394682348068244e+71
1.363729257042

In [13]:
print(g_thetas)  # final thetas

[[9.41034181e+76]
 [1.16123904e+76]
 [1.53927734e+76]
 [4.83694180e+74]]


In [14]:
print(thetas)  # inital thetas


[[100]
 [ 50]
 [ 75]
 [  1]]


In [15]:
# By looking at the inital thetas and final thetas we can see the linear relationship between features and outputs

# Task-2

In [16]:
X = np.array([[1,2,3,4,5] , [1,1,1,1,1]]).T
Y = np.array([[1],[4],[9],[16],[25]])
n_thetas = np.array([[10] , [1]])
thetas = n_thetas
alpha = 0.08

In [17]:

for i in range(100):
    y_pred = hypothesis(X , n_thetas)
    g_thetas = der_loss_fun(X , Y , n_thetas)
    g_thetas = g_thetas.T
    n_thetas = gradient_descent (alpha , n_thetas , g_thetas)
    print(loss_fun(Y , y_pred))

434.8
348.3744000000001
279.4023475200002
224.35029243494427
180.40054056289597
145.3062043758643
117.27554546336822
94.87975294182503
76.97940886346149
62.6658539855077
51.214434569329626
42.04722270357208
34.70329049209911
28.815007438891495
24.089140529766155
20.29178382733688
17.236341596959303
14.773946222648524
12.785817550483078
11.177170269350121
9.872355653254125
8.810987550801286
7.944853189061253
7.235449770705344
6.652020066179821
6.169985896044296
5.769698885599036
5.435444209540042
5.154646069834654
4.9172340360606315
4.715137658935371
4.541883371139287
4.392272954852356
4.262127053814067
4.1480805553806634
4.04741933737741
3.9579500029822148
3.8778959240326216
3.80581426641388
3.7405297502447596
3.6810817579939212
3.6266820897368177
3.5766812118283644
3.530541281488044
3.487814577631601
3.4481262456475106
3.4111604849850083
3.3766494847823743
3.344364553396858
3.314108999841305
3.2857124145596863
3.259026068286927
3.2339192046078926
3.2102760471828327
3.1879933787747206


In [18]:
n_thetas # old thetas

array([[ 5.88581987],
       [-6.58750195]])

In [19]:
thetas  # initial thetas

array([[10],
       [ 1]])

# Task-3

Question: Is linear regression good for classification? If yes, then why, and if no, then why?

Answer:
Linear regression is not suitable because it only works for continuos values whereas classification problems mandate discrete values. 

# Task-4

Question: Why do we use mse (mean squared error) over squared error? What is the benefit of mse?

Answer: MSE calculates the average squared difference between the observed and predicted values. When a model has no error, the MSE equals zero. As model error increases, its value increases.

# Task-5

Question: Can you find a better estimator than mse?

Answer: MSE is a function of the parameter, there will not be one “best” estimator in terms of MSE.