In [1]:
import numpy as np

# Create a numpy array of int, characters, float and find their shapes

In [2]:
integers = np.random.randint(1,10,5)
print("Array: \n" , integers)
print("Shape: \n" , integers.shape)

Array: 
 [8 6 9 5 3]
Shape: 
 (5,)


In [3]:
floats = np.random.random(5)
print("Array: \n" , floats)
print("Shape: \n" , floats.shape)

Array: 
 [0.44694176 0.65646103 0.87815417 0.17770928 0.96096937]
Shape: 
 (5,)


In [4]:
x = np.random.randint(65 , 91 , 10)

char_arr = [0]*10
count=0
for i in x:
    
    char_arr[count] = chr(i)
    count+=1


char_arr = np.array(char_arr)
print(char_arr)

['F' 'R' 'Z' 'I' 'B' 'D' 'Q' 'G' 'K' 'N']


# Create a zeros, empty, identity , eye and a full array

In [5]:
zers_array = np.zeros(10)
zers_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
identity = np.identity(10)
identity

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [7]:
eye_matrix = np.eye(4,3)
eye_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [8]:
empty = np.empty(10)
empty

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
full = np.full(8,1)
full

array([1, 1, 1, 1, 1, 1, 1, 1])

# Declare an array having the datatype of object, is it possible?

In [10]:
object_type = np.array([1,0.5,3,'a','ans'] , dtype=object)
object_type

array([1, 0.5, 3, 'a', 'ans'], dtype=object)

# Create an array having 5 equally spaced numbers ranging from 5 to 15

In [11]:
ran = np.linspace(5,15,5)
ran

array([ 5. ,  7.5, 10. , 12.5, 15. ])

# Create a numpy array ranging from 1 to 100.

In [12]:
aran = np.arange(1,101)
aran

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

# Reshape the above array into (100,15). Is it possible?

In [13]:
# not posssible

# Reshape the array into (10,10).

In [14]:
resh = aran.reshape(10, 10)
resh

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

# Flatten and ravel the reshaped array. What is the difference?

In [15]:
flat = resh.flatten()
flat

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [16]:
rav = resh.ravel()
rav

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [17]:
#flatten deep copy and faster than ravel
#ravel shallow copy and slower than flatten

# Take an array [[1 2 3] [4 5 6] [ 7 8 9]]. Sum it along 0 and 1 axis

In [18]:
arr = np.array([[1,2,3] , [4,5,6] , [7,8,9]])

row_sum = np.sum(arr , axis=1)
col_sum = np.sum(arr , axis=0)
print("Row vice sum: " , row_sum)
print("Column vice sum: " , col_sum)


Row vice sum:  [ 6 15 24]
Column vice sum:  [12 15 18]


# Find the number of bytes used by your array

In [19]:
siz = arr.nbytes
siz

36

# Find the maximum and minimum values in a 1D array.

In [20]:
D1_array = np.array([1,2,3,4,5,99,34])
max_index = np.argmax(D1_array)
min_index = np.argmin(D1_array)

print("Max Value: " , D1_array[max_index])
print("Min Value: " , D1_array[min_index])

Max Value:  99
Min Value:  1


# Find the maximum and minimum values in 2D array

In [21]:
arr = np.array([[1,2,3] , [4,5,6] , [7,8,9]])

column_max = np.amax(arr , axis=0)
column_min = np.min(arr , axis=0)
row_max = np.amax(arr , axis=1)
row_min = np.min(arr , axis=1)

print("Array: \n" , arr)
print("Column min: " , column_min)
print("Column max: " , column_max)
print("Row min: " , row_min)
print("Row max: " , row_max)

Array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Column min:  [1 2 3]
Column max:  [7 8 9]
Row min:  [1 4 7]
Row max:  [3 6 9]


# Sort an array

In [22]:
D1_array = np.array([1,2,3,4,5,99,34])
sort_array= np.sort(D1_array)
sort_array


array([ 1,  2,  3,  4,  5, 34, 99])

# Is * and mul the same as dot product for numpy arrays and matrices? Check.

In [23]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

dot = np.dot(arr1 , arr2)
mul = arr1 * arr2

print("Dot Product: " , dot)
print("*: " , mul)


Dot Product:  32
*:  [ 4 10 18]


In [24]:
# both are not same

# Take the square root and norm of an array.

In [25]:
a = [1,4,9,16]
sqrt = np.sqrt(a)
norm = np.linalg.norm(a)

print("Square Root: " , sqrt)
print("Normalize: " , norm)

Square Root:  [1. 2. 3. 4.]
Normalize:  18.81488772222678


# Find the std, non-zero, zero values and mean of an array.

In [26]:
std = np.std(a)
mean= np.mean(a)

a = np.array([1,3,6,0,7])
zeros = a[a==0]
non_zeros = a[a!=0]
print("std: " , std)
print("mean: ", mean)
print("Non zeros: ", non_zeros)
print("Zeros: " , zeros)

std:  5.678908345800274
mean:  7.5
Non zeros:  [1 3 6 7]
Zeros:  [0]


# Convert some angles to radians and vice versa.

In [27]:
angles = np.random.uniform(0,360,10)

print("Array: " , angles)
rad   = np.radians(angles)
print("Radians: " , rad)
angle = np.degrees(rad)
print("Angles: " , angle )

Array:  [ 33.94058575 207.69217706 356.75340517 295.7490672   21.23529578
  18.5741619   10.53876454 313.16418143 242.06842582  16.41031073]
Radians:  [0.59237497 3.62491232 6.22652154 5.16179498 0.37062583 0.32418028
 0.18393614 5.46574607 4.22489105 0.28641395]
Angles:  [ 33.94058575 207.69217706 356.75340517 295.7490672   21.23529578
  18.5741619   10.53876454 313.16418143 242.06842582  16.41031073]


# Save and load some of your arrays

In [28]:
arr = np.array([1,2,3,4])
np.save('array' , arr)


In [29]:
np.load('array.npy')

array([1, 2, 3, 4])

# Calculate the mean, std, var, max, min, of an array with shape (3,3,12,3) containing floats drawn
from a normal distribution with mean 21 and sigma 4.5. see the np.random.normal.

In [30]:
arr = np.random.normal(21,4.5,[3,3,12,3])
arr

array([[[[21.41625936, 18.19286464, 26.91245995],
         [14.29162696, 24.79475312, 26.70005426],
         [20.74508275, 20.13547318, 26.37190813],
         [19.96512586, 21.07304475, 26.21469321],
         [14.48025904, 18.98503123, 17.47658834],
         [22.03326185, 25.97368375, 21.67316456],
         [23.35030439, 23.38278282, 25.21108147],
         [17.01712873, 20.71658641, 28.01444037],
         [15.42395628, 16.28699656, 12.12745139],
         [24.67825413, 18.5215206 , 19.69133187],
         [16.81698647, 19.16478376, 25.1350121 ],
         [23.82387648, 31.41777874, 18.77973846]],

        [[30.07106888, 22.37529905, 19.20386374],
         [17.68341467, 17.42830824, 19.30452429],
         [20.34395358, 24.22197996, 19.21427568],
         [17.6294411 , 18.35921455, 24.74517162],
         [20.21032011, 21.30132638, 26.55927952],
         [17.73817712, 20.26160547, 25.02543894],
         [19.98362609, 22.93645772, 28.2083849 ],
         [12.11443072, 21.54012501, 25.54797644]

In [31]:
print("Mean: " , np.mean(arr))
print("Std: " , np.std(arr))
print("Var: " , np.var(arr))
print("Min: " , np.min(arr))
print("Max: " , np.max(arr))

Mean:  21.66420469362135
Std:  4.2536359180471335
Var:  18.09341852330068
Min:  11.818419516367435
Max:  33.15644560779286
